[project]
name = "molecular_qm_turbomole"
dynamic = ["version"]
description = "TURBOMOLE capabilities for molecular quantum mechanics within the Simstack framework"
readme = "molecular_qm_turbomole/README.md"
requires-python = ">=3.12, <3.13"
license = { text = "MIT" }
authors = [
  { name = "Wolfgang Wenzel", email = "wolfgang.wenzel@kit.edu" }
]
dependencies = [
    "molecular_qm_models",
    "molecular_qm_util",
    "simstack",
]

[project.entry-points."simstack.modules"]
molecular_qm_turbomole = "molecular_qm_turbomole"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.1.0.dev0"

[tool.hatch.version.raw-options]
version_scheme = "release-branch-semver"
local_scheme = "no-local-version"

[tool.hatch.build.hooks.vcs]
version-file = "molecular_qm_turbomole/_version.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["molecular_qm_turbomole"]

[tool.hatch.build.targets.wheel.force-include]
"molecular_qm_turbomole/lib/scripts" = "molecular_qm_turbomole/lib/scripts"

[tool.uv.sources]
molecular_qm_models = { git = "https://github.com/simstack/molecular_qm_models.git" }
molecular_qm_util = { git = "https://github.com/simstack/molecular_qm_util.git" }
simstack = { git = "https://github.com/simstack/simstack.git", rev = "celso-simstack" }

[tool.uv]
override-dependencies = [
    "molecular_qm_models @ git+https://github.com/simstack/molecular_qm_models.git",
    "molecular_qm_util @ git+https://github.com/simstack/molecular_qm_util.git",
    "simstack @ git+https://github.com/simstack/simstack.git@celso-simstack",
]


[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "pytest-asyncio>=1.3.0",
]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
testpaths = ["molecular_qm_turbomole/tests"]
